package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Autocph implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.293+08:00", comments="Source field: AutoCPH.CPH")
    private String cph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AutoCPH
     *
     * @mbg.generated Fri Jul 05 20:12:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.296+08:00", comments="Source field: AutoCPH.CPH")
    public String getCph() {
        return cph;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.297+08:00", comments="Source field: AutoCPH.CPH")
    public void setCph(String cph) {
        this.cph = cph == null ? null : cph.trim();
    }
}