package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class DtDoorHoliday implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.sDate")
    private String sdate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.DevcNum")
    private Integer devcnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Dt_Door_Holiday
     *
     * @mbg.generated Fri Jul 05 20:12:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.sDate")
    public String getSdate() {
        return sdate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.sDate")
    public void setSdate(String sdate) {
        this.sdate = sdate == null ? null : sdate.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.DevcNum")
    public Integer getDevcnum() {
        return devcnum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.367+08:00", comments="Source field: Dt_Door_Holiday.DevcNum")
    public void setDevcnum(Integer devcnum) {
        this.devcnum = devcnum;
    }
}