package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class MCardtype implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carid")
    private Integer carid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carCname")
    private String carcname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carEname")
    private String carename;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.712+08:00", comments="Source field: M_CardType.carMark")
    private String carmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_CardType
     *
     * @mbg.generated Fri Jul 05 20:12:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carid")
    public Integer getCarid() {
        return carid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carid")
    public void setCarid(Integer carid) {
        this.carid = carid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carCname")
    public String getCarcname() {
        return carcname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.711+08:00", comments="Source field: M_CardType.carCname")
    public void setCarcname(String carcname) {
        this.carcname = carcname == null ? null : carcname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.712+08:00", comments="Source field: M_CardType.carEname")
    public String getCarename() {
        return carename;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.712+08:00", comments="Source field: M_CardType.carEname")
    public void setCarename(String carename) {
        this.carename = carename == null ? null : carename.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.712+08:00", comments="Source field: M_CardType.carMark")
    public String getCarmark() {
        return carmark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-05T20:12:44.712+08:00", comments="Source field: M_CardType.carMark")
    public void setCarmark(String carmark) {
        this.carmark = carmark == null ? null : carmark.trim();
    }
}