package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class MDoormapsdoorinfo implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Mapid")
    private Integer mapid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Drawing")
    private String drawing;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcID")
    private String devcid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcName")
    private String devcname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Doorid")
    private String doorid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.854+08:00", comments="Source field: M_DoorMapsDoorInfo.DoorName")
    private String doorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table M_DoorMapsDoorInfo
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Mapid")
    public Integer getMapid() {
        return mapid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Mapid")
    public void setMapid(Integer mapid) {
        this.mapid = mapid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Drawing")
    public String getDrawing() {
        return drawing;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.Drawing")
    public void setDrawing(String drawing) {
        this.drawing = drawing == null ? null : drawing.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcID")
    public String getDevcid() {
        return devcid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcID")
    public void setDevcid(String devcid) {
        this.devcid = devcid == null ? null : devcid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcName")
    public String getDevcname() {
        return devcname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.853+08:00", comments="Source field: M_DoorMapsDoorInfo.DevcName")
    public void setDevcname(String devcname) {
        this.devcname = devcname == null ? null : devcname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.854+08:00", comments="Source field: M_DoorMapsDoorInfo.Doorid")
    public String getDoorid() {
        return doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.854+08:00", comments="Source field: M_DoorMapsDoorInfo.Doorid")
    public void setDoorid(String doorid) {
        this.doorid = doorid == null ? null : doorid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.854+08:00", comments="Source field: M_DoorMapsDoorInfo.DoorName")
    public String getDoorname() {
        return doorname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.854+08:00", comments="Source field: M_DoorMapsDoorInfo.DoorName")
    public void setDoorname(String doorname) {
        this.doorname = doorname == null ? null : doorname.trim();
    }
}