package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Mjdowncardouttimesettb implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.627+08:00", comments="Source field: MJDownCardOutTimeSettb.outtime")
    private Integer outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MJDownCardOutTimeSettb
     *
     * @mbg.generated Thu Jul 18 14:55:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.627+08:00", comments="Source field: MJDownCardOutTimeSettb.outtime")
    public Integer getOuttime() {
        return outtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.627+08:00", comments="Source field: MJDownCardOutTimeSettb.outtime")
    public void setOuttime(Integer outtime) {
        this.outtime = outtime;
    }
}