package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class MyAuthorization implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.446+08:00", comments="Source field: My_Authorization.bAuthorization")
    private Boolean bauthorization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table My_Authorization
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.446+08:00", comments="Source field: My_Authorization.bAuthorization")
    public Boolean getBauthorization() {
        return bauthorization;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.446+08:00", comments="Source field: My_Authorization.bAuthorization")
    public void setBauthorization(Boolean bauthorization) {
        this.bauthorization = bauthorization;
    }
}