package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class Myblacklist implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.ID")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.CPH")
    private String cph;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.StartTime")
    private Date starttime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.EndTime")
    private Date endtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.Reason")
    private String reason;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.DownloadSignal")
    private String downloadsignal;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.AddDelete")
    private Integer adddelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYBlacklist
     *
     * @mbg.generated Tue Jul 16 10:08:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.CPH")
    public String getCph() {
        return cph;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.CPH")
    public void setCph(String cph) {
        this.cph = cph == null ? null : cph.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.StartTime")
    public Date getStarttime() {
        return starttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.StartTime")
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.EndTime")
    public Date getEndtime() {
        return endtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.EndTime")
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.Reason")
    public String getReason() {
        return reason;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.Reason")
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.DownloadSignal")
    public String getDownloadsignal() {
        return downloadsignal;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.DownloadSignal")
    public void setDownloadsignal(String downloadsignal) {
        this.downloadsignal = downloadsignal == null ? null : downloadsignal.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.AddDelete")
    public Integer getAdddelete() {
        return adddelete;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.642+08:00", comments="Source field: MYBlacklist.AddDelete")
    public void setAdddelete(Integer adddelete) {
        this.adddelete = adddelete;
    }
}