package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Mycardtype implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.ID")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.CardType")
    private String cardtype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Identifying")
    private String identifying;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Enabled")
    private Boolean enabled;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Reamrks")
    private String reamrks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYCardType
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.CardType")
    public String getCardtype() {
        return cardtype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.CardType")
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Identifying")
    public String getIdentifying() {
        return identifying;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Identifying")
    public void setIdentifying(String identifying) {
        this.identifying = identifying == null ? null : identifying.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Enabled")
    public Boolean getEnabled() {
        return enabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Enabled")
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Reamrks")
    public String getReamrks() {
        return reamrks;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.358+08:00", comments="Source field: MYCardType.Reamrks")
    public void setReamrks(String reamrks) {
        this.reamrks = reamrks == null ? null : reamrks.trim();
    }
}