package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Mychechangstatus implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.PCName")
    private String pcname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.Online")
    private Integer online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYCHECHANGSTATUS
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.PCName")
    public String getPcname() {
        return pcname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.PCName")
    public void setPcname(String pcname) {
        this.pcname = pcname == null ? null : pcname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.Online")
    public Integer getOnline() {
        return online;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.728+08:00", comments="Source field: MYCHECHANGSTATUS.Online")
    public void setOnline(Integer online) {
        this.online = online;
    }
}