package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;

public class Myicmoney implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.ID")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.CardNO")
    private String cardno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.OptDate")
    private Date optdate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.SFJE")
    private BigDecimal sfje;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.Balance")
    private BigDecimal balance;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.OperatorCardNO")
    private String operatorcardno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.OptType")
    private String opttype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewStartDate")
    private Date newstartdate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewEndDate")
    private Date newenddate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.LastEndDate")
    private Date lastenddate;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.Remark")
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYICMONEY
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.CardNO")
    public String getCardno() {
        return cardno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.CardNO")
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.OptDate")
    public Date getOptdate() {
        return optdate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.OptDate")
    public void setOptdate(Date optdate) {
        this.optdate = optdate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.SFJE")
    public BigDecimal getSfje() {
        return sfje;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.SFJE")
    public void setSfje(BigDecimal sfje) {
        this.sfje = sfje;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.Balance")
    public BigDecimal getBalance() {
        return balance;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.Balance")
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.767+08:00", comments="Source field: MYICMONEY.OperatorCardNO")
    public String getOperatorcardno() {
        return operatorcardno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.OperatorCardNO")
    public void setOperatorcardno(String operatorcardno) {
        this.operatorcardno = operatorcardno == null ? null : operatorcardno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.OptType")
    public String getOpttype() {
        return opttype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.OptType")
    public void setOpttype(String opttype) {
        this.opttype = opttype == null ? null : opttype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewStartDate")
    public Date getNewstartdate() {
        return newstartdate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewStartDate")
    public void setNewstartdate(Date newstartdate) {
        this.newstartdate = newstartdate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewEndDate")
    public Date getNewenddate() {
        return newenddate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.NewEndDate")
    public void setNewenddate(Date newenddate) {
        this.newenddate = newenddate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.LastEndDate")
    public Date getLastenddate() {
        return lastenddate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.LastEndDate")
    public void setLastenddate(Date lastenddate) {
        this.lastenddate = lastenddate;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.Remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.768+08:00", comments="Source field: MYICMONEY.Remark")
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}