package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Mymianfeishiyou implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemID")
    private Integer itemid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemDetail")
    private String itemdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYMIANFEISHIYOU
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemID")
    public Integer getItemid() {
        return itemid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemID")
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemDetail")
    public String getItemdetail() {
        return itemdetail;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.777+08:00", comments="Source field: MYMIANFEISHIYOU.ItemDetail")
    public void setItemdetail(String itemdetail) {
        this.itemdetail = itemdetail == null ? null : itemdetail.trim();
    }
}