package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class Myparkinggreeting implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.CtrlNumber")
    private Integer ctrlnumber;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.Voice")
    private String voice;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.StartTime")
    private Date starttime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.EndTime")
    private Date endtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.DredgeVoice")
    private Boolean dredgevoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MyParkingGreeting
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.CtrlNumber")
    public Integer getCtrlnumber() {
        return ctrlnumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.CtrlNumber")
    public void setCtrlnumber(Integer ctrlnumber) {
        this.ctrlnumber = ctrlnumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.Voice")
    public String getVoice() {
        return voice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.Voice")
    public void setVoice(String voice) {
        this.voice = voice == null ? null : voice.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.StartTime")
    public Date getStarttime() {
        return starttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.885+08:00", comments="Source field: MyParkingGreeting.StartTime")
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.EndTime")
    public Date getEndtime() {
        return endtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.EndTime")
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.DredgeVoice")
    public Boolean getDredgevoice() {
        return dredgevoice;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.886+08:00", comments="Source field: MyParkingGreeting.DredgeVoice")
    public void setDredgevoice(Boolean dredgevoice) {
        this.dredgevoice = dredgevoice;
    }
}