package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Myscancodepay implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.SMPayment")
    private Boolean smpayment;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXAppID")
    private String wxappid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXMCHID")
    private String wxmchid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXKEY")
    private String wxkey;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBAppID")
    private String zfbappid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBPID")
    private String zfbpid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp1")
    private String strtemp1;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp2")
    private String strtemp2;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp3")
    private String strtemp3;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp4")
    private String strtemp4;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp5")
    private String strtemp5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MyScanCodePay
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.SMPayment")
    public Boolean getSmpayment() {
        return smpayment;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.SMPayment")
    public void setSmpayment(Boolean smpayment) {
        this.smpayment = smpayment;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXAppID")
    public String getWxappid() {
        return wxappid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXAppID")
    public void setWxappid(String wxappid) {
        this.wxappid = wxappid == null ? null : wxappid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXMCHID")
    public String getWxmchid() {
        return wxmchid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXMCHID")
    public void setWxmchid(String wxmchid) {
        this.wxmchid = wxmchid == null ? null : wxmchid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXKEY")
    public String getWxkey() {
        return wxkey;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.WXKEY")
    public void setWxkey(String wxkey) {
        this.wxkey = wxkey == null ? null : wxkey.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBAppID")
    public String getZfbappid() {
        return zfbappid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBAppID")
    public void setZfbappid(String zfbappid) {
        this.zfbappid = zfbappid == null ? null : zfbappid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBPID")
    public String getZfbpid() {
        return zfbpid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.ZFBPID")
    public void setZfbpid(String zfbpid) {
        this.zfbpid = zfbpid == null ? null : zfbpid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp1")
    public String getStrtemp1() {
        return strtemp1;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp1")
    public void setStrtemp1(String strtemp1) {
        this.strtemp1 = strtemp1 == null ? null : strtemp1.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp2")
    public String getStrtemp2() {
        return strtemp2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp2")
    public void setStrtemp2(String strtemp2) {
        this.strtemp2 = strtemp2 == null ? null : strtemp2.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp3")
    public String getStrtemp3() {
        return strtemp3;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp3")
    public void setStrtemp3(String strtemp3) {
        this.strtemp3 = strtemp3 == null ? null : strtemp3.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp4")
    public String getStrtemp4() {
        return strtemp4;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp4")
    public void setStrtemp4(String strtemp4) {
        this.strtemp4 = strtemp4 == null ? null : strtemp4.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp5")
    public String getStrtemp5() {
        return strtemp5;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.440+08:00", comments="Source field: MyScanCodePay.StrTemp5")
    public void setStrtemp5(String strtemp5) {
        this.strtemp5 = strtemp5 == null ? null : strtemp5.trim();
    }
}