package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Mytbmeishuoset implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.CtrlNumber")
    private Integer ctrlnumber;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.LockLocation")
    private String locklocation;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DeptName")
    private String deptname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DoorID")
    private String doorid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.PCName")
    private String pcname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.ProduceIndex")
    private String produceindex;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.CtrlType")
    private String ctrltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYTBMEISHUOSET
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.CtrlNumber")
    public Integer getCtrlnumber() {
        return ctrlnumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.CtrlNumber")
    public void setCtrlnumber(Integer ctrlnumber) {
        this.ctrlnumber = ctrlnumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.LockLocation")
    public String getLocklocation() {
        return locklocation;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.798+08:00", comments="Source field: MYTBMEISHUOSET.LockLocation")
    public void setLocklocation(String locklocation) {
        this.locklocation = locklocation == null ? null : locklocation.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DeptName")
    public String getDeptname() {
        return deptname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DeptName")
    public void setDeptname(String deptname) {
        this.deptname = deptname == null ? null : deptname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DoorID")
    public String getDoorid() {
        return doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.DoorID")
    public void setDoorid(String doorid) {
        this.doorid = doorid == null ? null : doorid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.PCName")
    public String getPcname() {
        return pcname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.PCName")
    public void setPcname(String pcname) {
        this.pcname = pcname == null ? null : pcname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.ProduceIndex")
    public String getProduceindex() {
        return produceindex;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.ProduceIndex")
    public void setProduceindex(String produceindex) {
        this.produceindex = produceindex == null ? null : produceindex.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.CtrlType")
    public String getCtrltype() {
        return ctrltype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.799+08:00", comments="Source field: MYTBMEISHUOSET.CtrlType")
    public void setCtrltype(String ctrltype) {
        this.ctrltype = ctrltype == null ? null : ctrltype.trim();
    }
}