package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Myvoicecardno implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.VoiceCardNO")
    private String voicecardno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.CtrlNumber")
    private Integer ctrlnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MyVoiceCardNO
     *
     * @mbg.generated Wed Jul 31 15:28:01 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.VoiceCardNO")
    public String getVoicecardno() {
        return voicecardno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.VoiceCardNO")
    public void setVoicecardno(String voicecardno) {
        this.voicecardno = voicecardno == null ? null : voicecardno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.CtrlNumber")
    public Integer getCtrlnumber() {
        return ctrlnumber;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-31T15:28:01.150+08:00", comments="Source field: MyVoiceCardNO.CtrlNumber")
    public void setCtrlnumber(Integer ctrlnumber) {
        this.ctrlnumber = ctrlnumber;
    }
}