package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.annotation.Generated;

public class Myzbparkautocph implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.ID")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.CPH")
    private String cph;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Address")
    private String address;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Favorable")
    private BigDecimal favorable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Manner")
    private String manner;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutHour")
    private BigDecimal outhour;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutDayNo")
    private BigDecimal outdayno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Enable")
    private Boolean enable;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.PCName")
    private String pcname;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OptTime")
    private Date opttime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Operator")
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MYZBPARKAutoCPH
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.ID")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.ID")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.CPH")
    public String getCph() {
        return cph;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.CPH")
    public void setCph(String cph) {
        this.cph = cph == null ? null : cph.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Address")
    public String getAddress() {
        return address;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Address")
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Favorable")
    public BigDecimal getFavorable() {
        return favorable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Favorable")
    public void setFavorable(BigDecimal favorable) {
        this.favorable = favorable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Manner")
    public String getManner() {
        return manner;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Manner")
    public void setManner(String manner) {
        this.manner = manner == null ? null : manner.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutHour")
    public BigDecimal getOuthour() {
        return outhour;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutHour")
    public void setOuthour(BigDecimal outhour) {
        this.outhour = outhour;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutDayNo")
    public BigDecimal getOutdayno() {
        return outdayno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OutDayNo")
    public void setOutdayno(BigDecimal outdayno) {
        this.outdayno = outdayno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Enable")
    public Boolean getEnable() {
        return enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Enable")
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.PCName")
    public String getPcname() {
        return pcname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.PCName")
    public void setPcname(String pcname) {
        this.pcname = pcname == null ? null : pcname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OptTime")
    public Date getOpttime() {
        return opttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.OptTime")
    public void setOpttime(Date opttime) {
        this.opttime = opttime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Operator")
    public String getOperator() {
        return operator;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.346+08:00", comments="Source field: MYZBPARKAutoCPH.Operator")
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }
}