package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class QrRecord implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.908+08:00", comments="Source field: Qr_Record.Cardid")
    private String cardid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Cardtype")
    private String cardtype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Userno")
    private String userno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.UserName")
    private String username;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Department")
    private String department;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machno")
    private String machno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machplace")
    private String machplace;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Doorno")
    private String doorno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Opentime")
    private String opentime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Qr_Record
     *
     * @mbg.generated Sun Jul 14 17:27:27 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.908+08:00", comments="Source field: Qr_Record.Cardid")
    public String getCardid() {
        return cardid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Cardid")
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Cardtype")
    public String getCardtype() {
        return cardtype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Cardtype")
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Userno")
    public String getUserno() {
        return userno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Userno")
    public void setUserno(String userno) {
        this.userno = userno == null ? null : userno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.UserName")
    public String getUsername() {
        return username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.UserName")
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Department")
    public String getDepartment() {
        return department;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Department")
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machno")
    public String getMachno() {
        return machno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machno")
    public void setMachno(String machno) {
        this.machno = machno == null ? null : machno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machplace")
    public String getMachplace() {
        return machplace;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Machplace")
    public void setMachplace(String machplace) {
        this.machplace = machplace == null ? null : machplace.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Doorno")
    public String getDoorno() {
        return doorno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Doorno")
    public void setDoorno(String doorno) {
        this.doorno = doorno == null ? null : doorno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Opentime")
    public String getOpentime() {
        return opentime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-14T17:27:27.909+08:00", comments="Source field: Qr_Record.Opentime")
    public void setOpentime(String opentime) {
        this.opentime = opentime == null ? null : opentime.trim();
    }
}