package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class SerDoorrealtimestuats implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.505+08:00", comments="Source field: Ser_DoorRealTimeStuats.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.506+08:00", comments="Source field: Ser_DoorRealTimeStuats.DoorName")
    private String doorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ser_DoorRealTimeStuats
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.505+08:00", comments="Source field: Ser_DoorRealTimeStuats.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.506+08:00", comments="Source field: Ser_DoorRealTimeStuats.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.506+08:00", comments="Source field: Ser_DoorRealTimeStuats.DoorName")
    public String getDoorname() {
        return doorname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.506+08:00", comments="Source field: Ser_DoorRealTimeStuats.DoorName")
    public void setDoorname(String doorname) {
        this.doorname = doorname == null ? null : doorname.trim();
    }
}