package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class SerDoordata implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.851+08:00", comments="Source field: Ser_DoorData.DevcNo")
    private Integer devcno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.851+08:00", comments="Source field: Ser_DoorData.Place")
    private String place;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DevcType")
    private Integer devctype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.Com")
    private Integer com;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DoorInfo")
    private String doorinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ser_DoorData
     *
     * @mbg.generated Thu Jul 18 14:55:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.851+08:00", comments="Source field: Ser_DoorData.DevcNo")
    public Integer getDevcno() {
        return devcno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.851+08:00", comments="Source field: Ser_DoorData.DevcNo")
    public void setDevcno(Integer devcno) {
        this.devcno = devcno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.Place")
    public String getPlace() {
        return place;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.Place")
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DevcType")
    public Integer getDevctype() {
        return devctype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DevcType")
    public void setDevctype(Integer devctype) {
        this.devctype = devctype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.Com")
    public Integer getCom() {
        return com;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.Com")
    public void setCom(Integer com) {
        this.com = com;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DoorInfo")
    public String getDoorinfo() {
        return doorinfo;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.852+08:00", comments="Source field: Ser_DoorData.DoorInfo")
    public void setDoorinfo(String doorinfo) {
        this.doorinfo = doorinfo == null ? null : doorinfo.trim();
    }
}