package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class SerTequanmode implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Devcid")
    private Integer devcid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Doorid")
    private Integer doorid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.946+08:00", comments="Source field: Ser_TeQuanMode.DoorMode")
    private String doormode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ser_TeQuanMode
     *
     * @mbg.generated Tue Jul 16 10:08:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Devcid")
    public Integer getDevcid() {
        return devcid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Devcid")
    public void setDevcid(Integer devcid) {
        this.devcid = devcid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Doorid")
    public Integer getDoorid() {
        return doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.945+08:00", comments="Source field: Ser_TeQuanMode.Doorid")
    public void setDoorid(Integer doorid) {
        this.doorid = doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.946+08:00", comments="Source field: Ser_TeQuanMode.DoorMode")
    public String getDoormode() {
        return doormode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.946+08:00", comments="Source field: Ser_TeQuanMode.DoorMode")
    public void setDoormode(String doormode) {
        this.doormode = doormode == null ? null : doormode.trim();
    }
}