package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class SerTimingopen implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DevcNum")
    private Integer devcnum;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DoorId")
    private Integer doorid;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.NoMalSet")
    private Integer nomalset;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.Week")
    private Integer week;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star1")
    private String star1;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end1")
    private String end1;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star2")
    private String star2;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end2")
    private String end2;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star3")
    private String star3;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end3")
    private String end3;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.star4")
    private String star4;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end4")
    private String end4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Ser_TimingOpen
     *
     * @mbg.generated Tue Jul 16 10:08:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DevcNum")
    public Integer getDevcnum() {
        return devcnum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DevcNum")
    public void setDevcnum(Integer devcnum) {
        this.devcnum = devcnum;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DoorId")
    public Integer getDoorid() {
        return doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.DoorId")
    public void setDoorid(Integer doorid) {
        this.doorid = doorid;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.NoMalSet")
    public Integer getNomalset() {
        return nomalset;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.NoMalSet")
    public void setNomalset(Integer nomalset) {
        this.nomalset = nomalset;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.Week")
    public Integer getWeek() {
        return week;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.Week")
    public void setWeek(Integer week) {
        this.week = week;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star1")
    public String getStar1() {
        return star1;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star1")
    public void setStar1(String star1) {
        this.star1 = star1 == null ? null : star1.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end1")
    public String getEnd1() {
        return end1;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end1")
    public void setEnd1(String end1) {
        this.end1 = end1 == null ? null : end1.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star2")
    public String getStar2() {
        return star2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.star2")
    public void setStar2(String star2) {
        this.star2 = star2 == null ? null : star2.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end2")
    public String getEnd2() {
        return end2;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.950+08:00", comments="Source field: Ser_TimingOpen.end2")
    public void setEnd2(String end2) {
        this.end2 = end2 == null ? null : end2.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.star3")
    public String getStar3() {
        return star3;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.star3")
    public void setStar3(String star3) {
        this.star3 = star3 == null ? null : star3.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end3")
    public String getEnd3() {
        return end3;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end3")
    public void setEnd3(String end3) {
        this.end3 = end3 == null ? null : end3.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.star4")
    public String getStar4() {
        return star4;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.star4")
    public void setStar4(String star4) {
        this.star4 = star4 == null ? null : star4.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end4")
    public String getEnd4() {
        return end4;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-16T10:08:57.951+08:00", comments="Source field: Ser_TimingOpen.end4")
    public void setEnd4(String end4) {
        this.end4 = end4 == null ? null : end4.trim();
    }
}