package cn.xvkang.primaryentity;

import java.io.Serializable;
import javax.annotation.Generated;

public class Tblquery implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Window")
    private String window;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SaveName")
    private String savename;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_CN")
    private String showfieldCn;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_EN")
    private String showfieldEn;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.RealField")
    private String realfield;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.OP")
    private String op;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SearchValue")
    private String searchvalue;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.DataType")
    private String datatype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Selected")
    private Byte selected;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.CurrentShow")
    private Byte currentshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tblQuery
     *
     * @mbg.generated Thu Jul 18 14:55:17 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Window")
    public String getWindow() {
        return window;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Window")
    public void setWindow(String window) {
        this.window = window == null ? null : window.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SaveName")
    public String getSavename() {
        return savename;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SaveName")
    public void setSavename(String savename) {
        this.savename = savename == null ? null : savename.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_CN")
    public String getShowfieldCn() {
        return showfieldCn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_CN")
    public void setShowfieldCn(String showfieldCn) {
        this.showfieldCn = showfieldCn == null ? null : showfieldCn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_EN")
    public String getShowfieldEn() {
        return showfieldEn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.ShowField_EN")
    public void setShowfieldEn(String showfieldEn) {
        this.showfieldEn = showfieldEn == null ? null : showfieldEn.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.RealField")
    public String getRealfield() {
        return realfield;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.RealField")
    public void setRealfield(String realfield) {
        this.realfield = realfield == null ? null : realfield.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.OP")
    public String getOp() {
        return op;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.OP")
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SearchValue")
    public String getSearchvalue() {
        return searchvalue;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.SearchValue")
    public void setSearchvalue(String searchvalue) {
        this.searchvalue = searchvalue == null ? null : searchvalue.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.DataType")
    public String getDatatype() {
        return datatype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.DataType")
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Selected")
    public Byte getSelected() {
        return selected;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.Selected")
    public void setSelected(Byte selected) {
        this.selected = selected;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.CurrentShow")
    public Byte getCurrentshow() {
        return currentshow;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-18T14:55:17.888+08:00", comments="Source field: tblQuery.CurrentShow")
    public void setCurrentshow(Byte currentshow) {
        this.currentshow = currentshow;
    }
}