package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.util.Date;
import javax.annotation.Generated;

public class Weiguijilu implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.user_id")
    private Integer userId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.remark")
    private String remark;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.cph")
    private String cph;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.createtime")
    private Date createtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.base64image")
    private String base64image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weiguijilu
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.user_id")
    public Integer getUserId() {
        return userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.user_id")
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.remark")
    public String getRemark() {
        return remark;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.remark")
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.cph")
    public String getCph() {
        return cph;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.cph")
    public void setCph(String cph) {
        this.cph = cph == null ? null : cph.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.createtime")
    public Date getCreatetime() {
        return createtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.createtime")
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.base64image")
    public String getBase64image() {
        return base64image;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.557+08:00", comments="Source field: weiguijilu.base64image")
    public void setBase64image(String base64image) {
        this.base64image = base64image == null ? null : base64image.trim();
    }
}