package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.annotation.Generated;

public class ZhMthcarcharge implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.carNo")
    private String carno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.beginTime")
    private String begintime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.endTime")
    private String endtime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeTime")
    private String chargetime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeMoney")
    private BigDecimal chargemoney;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.synflag")
    private Integer synflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zh_MthCarCharge
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.carNo")
    public String getCarno() {
        return carno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.carNo")
    public void setCarno(String carno) {
        this.carno = carno == null ? null : carno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.544+08:00", comments="Source field: zh_MthCarCharge.beginTime")
    public String getBegintime() {
        return begintime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.beginTime")
    public void setBegintime(String begintime) {
        this.begintime = begintime == null ? null : begintime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.endTime")
    public String getEndtime() {
        return endtime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.endTime")
    public void setEndtime(String endtime) {
        this.endtime = endtime == null ? null : endtime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeTime")
    public String getChargetime() {
        return chargetime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeTime")
    public void setChargetime(String chargetime) {
        this.chargetime = chargetime == null ? null : chargetime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeMoney")
    public BigDecimal getChargemoney() {
        return chargemoney;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.chargeMoney")
    public void setChargemoney(BigDecimal chargemoney) {
        this.chargemoney = chargemoney;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.synflag")
    public Integer getSynflag() {
        return synflag;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.545+08:00", comments="Source field: zh_MthCarCharge.synflag")
    public void setSynflag(Integer synflag) {
        this.synflag = synflag;
    }
}