package cn.xvkang.primaryentity;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.annotation.Generated;

public class ZhPayorder implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.id")
    private Integer id;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payOrderNo")
    private String payorderno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.orderNo")
    private String orderno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carNo")
    private String carno;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carType")
    private String cartype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payTime")
    private String paytime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payMoney")
    private BigDecimal paymoney;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payType")
    private String paytype;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.enterTime")
    private String entertime;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.synflag")
    private Integer synflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zh_PayOrder
     *
     * @mbg.generated Fri Jul 19 09:31:22 CST 2019
     */
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payOrderNo")
    public String getPayorderno() {
        return payorderno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payOrderNo")
    public void setPayorderno(String payorderno) {
        this.payorderno = payorderno == null ? null : payorderno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.orderNo")
    public String getOrderno() {
        return orderno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.orderNo")
    public void setOrderno(String orderno) {
        this.orderno = orderno == null ? null : orderno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carNo")
    public String getCarno() {
        return carno;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carNo")
    public void setCarno(String carno) {
        this.carno = carno == null ? null : carno.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carType")
    public String getCartype() {
        return cartype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.carType")
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payTime")
    public String getPaytime() {
        return paytime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payTime")
    public void setPaytime(String paytime) {
        this.paytime = paytime == null ? null : paytime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payMoney")
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payMoney")
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payType")
    public String getPaytype() {
        return paytype;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.payType")
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.enterTime")
    public String getEntertime() {
        return entertime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.enterTime")
    public void setEntertime(String entertime) {
        this.entertime = entertime == null ? null : entertime.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.synflag")
    public Integer getSynflag() {
        return synflag;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2019-07-19T09:31:22.548+08:00", comments="Source field: zh_PayOrder.synflag")
    public void setSynflag(Integer synflag) {
        this.synflag = synflag;
    }
}