// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/my_message.proto

package cn.xvkang.phone.netty.protobuf;

public final class MyMessage {
  private MyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .tutorial.Data.DataType data_type = 1;</code>
     */
    boolean hasDataType();
    /**
     * <code>required .tutorial.Data.DataType data_type = 1;</code>
     */
    cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType getDataType();

    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    boolean hasOpenData();
    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    cn.xvkang.phone.netty.protobuf.MyMessage.Open getOpenData();
    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder getOpenDataOrBuilder();

    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    boolean hasCloseData();
    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    cn.xvkang.phone.netty.protobuf.MyMessage.Close getCloseData();
    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder getCloseDataOrBuilder();

    public cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code tutorial.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Data)
      DataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Data() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType value = cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                dataType_ = rawValue;
              }
              break;
            }
            case 18: {
              cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(cn.xvkang.phone.netty.protobuf.MyMessage.Open.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(cn.xvkang.phone.netty.protobuf.MyMessage.Close.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.xvkang.phone.netty.protobuf.MyMessage.Data.class, cn.xvkang.phone.netty.protobuf.MyMessage.Data.Builder.class);
    }

    /**
     * Protobuf enum {@code tutorial.Data.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OPEN = 0;</code>
       */
      OPEN(0),
      /**
       * <code>CLOSE = 1;</code>
       */
      CLOSE(1),
      ;

      /**
       * <code>OPEN = 0;</code>
       */
      public static final int OPEN_VALUE = 0;
      /**
       * <code>CLOSE = 1;</code>
       */
      public static final int CLOSE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return OPEN;
          case 1: return CLOSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.Data.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tutorial.Data.DataType)
    }

    private int bitField0_;
    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      OPENDATA(2),
      CLOSEDATA(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return OPENDATA;
          case 3: return CLOSEDATA;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>required .tutorial.Data.DataType data_type = 1;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .tutorial.Data.DataType data_type = 1;</code>
     */
    public cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType getDataType() {
      @SuppressWarnings("deprecation")
      cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType result = cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType.valueOf(dataType_);
      return result == null ? cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType.OPEN : result;
    }

    public static final int OPENDATA_FIELD_NUMBER = 2;
    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    public boolean hasOpenData() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    public cn.xvkang.phone.netty.protobuf.MyMessage.Open getOpenData() {
      if (dataBodyCase_ == 2) {
         return (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_;
      }
      return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
    }
    /**
     * <code>optional .tutorial.Open openData = 2;</code>
     */
    public cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder getOpenDataOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_;
      }
      return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
    }

    public static final int CLOSEDATA_FIELD_NUMBER = 3;
    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    public boolean hasCloseData() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    public cn.xvkang.phone.netty.protobuf.MyMessage.Close getCloseData() {
      if (dataBodyCase_ == 3) {
         return (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_;
      }
      return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
    }
    /**
     * <code>optional .tutorial.Close closeData = 3;</code>
     */
    public cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder getCloseDataOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_;
      }
      return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Data)) {
        return super.equals(obj);
      }
      cn.xvkang.phone.netty.protobuf.MyMessage.Data other = (cn.xvkang.phone.netty.protobuf.MyMessage.Data) obj;

      if (hasDataType() != other.hasDataType()) return false;
      if (hasDataType()) {
        if (dataType_ != other.dataType_) return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getOpenData()
              .equals(other.getOpenData())) return false;
          break;
        case 3:
          if (!getCloseData()
              .equals(other.getCloseData())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDataType()) {
        hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + dataType_;
      }
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + OPENDATA_FIELD_NUMBER;
          hash = (53 * hash) + getOpenData().hashCode();
          break;
        case 3:
          hash = (37 * hash) + CLOSEDATA_FIELD_NUMBER;
          hash = (53 * hash) + getCloseData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.xvkang.phone.netty.protobuf.MyMessage.Data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Data)
        cn.xvkang.phone.netty.protobuf.MyMessage.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.xvkang.phone.netty.protobuf.MyMessage.Data.class, cn.xvkang.phone.netty.protobuf.MyMessage.Data.Builder.class);
      }

      // Construct using cn.xvkang.phone.netty.protobuf.MyMessage.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Data_descriptor;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Data getDefaultInstanceForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.Data.getDefaultInstance();
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Data build() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Data buildPartial() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Data result = new cn.xvkang.phone.netty.protobuf.MyMessage.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (openDataBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = openDataBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (closeDataBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = closeDataBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Data) {
          return mergeFrom((cn.xvkang.phone.netty.protobuf.MyMessage.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.xvkang.phone.netty.protobuf.MyMessage.Data other) {
        if (other == cn.xvkang.phone.netty.protobuf.MyMessage.Data.getDefaultInstance()) return this;
        if (other.hasDataType()) {
          setDataType(other.getDataType());
        }
        switch (other.getDataBodyCase()) {
          case OPENDATA: {
            mergeOpenData(other.getOpenData());
            break;
          }
          case CLOSEDATA: {
            mergeCloseData(other.getCloseData());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDataType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.xvkang.phone.netty.protobuf.MyMessage.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.xvkang.phone.netty.protobuf.MyMessage.Data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int dataType_ = 0;
      /**
       * <code>required .tutorial.Data.DataType data_type = 1;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .tutorial.Data.DataType data_type = 1;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType getDataType() {
        @SuppressWarnings("deprecation")
        cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType result = cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType.valueOf(dataType_);
        return result == null ? cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType.OPEN : result;
      }
      /**
       * <code>required .tutorial.Data.DataType data_type = 1;</code>
       */
      public Builder setDataType(cn.xvkang.phone.netty.protobuf.MyMessage.Data.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .tutorial.Data.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cn.xvkang.phone.netty.protobuf.MyMessage.Open, cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder> openDataBuilder_;
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public boolean hasOpenData() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.Open getOpenData() {
        if (openDataBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_;
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return openDataBuilder_.getMessage();
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public Builder setOpenData(cn.xvkang.phone.netty.protobuf.MyMessage.Open value) {
        if (openDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          openDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public Builder setOpenData(
          cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder builderForValue) {
        if (openDataBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          openDataBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public Builder mergeOpenData(cn.xvkang.phone.netty.protobuf.MyMessage.Open value) {
        if (openDataBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance()) {
            dataBody_ = cn.xvkang.phone.netty.protobuf.MyMessage.Open.newBuilder((cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            openDataBuilder_.mergeFrom(value);
          }
          openDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public Builder clearOpenData() {
        if (openDataBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          openDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder getOpenDataBuilder() {
        return getOpenDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder getOpenDataOrBuilder() {
        if ((dataBodyCase_ == 2) && (openDataBuilder_ != null)) {
          return openDataBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_;
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.Open openData = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.xvkang.phone.netty.protobuf.MyMessage.Open, cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder> 
          getOpenDataFieldBuilder() {
        if (openDataBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
          }
          openDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.xvkang.phone.netty.protobuf.MyMessage.Open, cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder>(
                  (cn.xvkang.phone.netty.protobuf.MyMessage.Open) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return openDataBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          cn.xvkang.phone.netty.protobuf.MyMessage.Close, cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder> closeDataBuilder_;
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public boolean hasCloseData() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.Close getCloseData() {
        if (closeDataBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_;
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return closeDataBuilder_.getMessage();
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public Builder setCloseData(cn.xvkang.phone.netty.protobuf.MyMessage.Close value) {
        if (closeDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          closeDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public Builder setCloseData(
          cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder builderForValue) {
        if (closeDataBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          closeDataBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public Builder mergeCloseData(cn.xvkang.phone.netty.protobuf.MyMessage.Close value) {
        if (closeDataBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance()) {
            dataBody_ = cn.xvkang.phone.netty.protobuf.MyMessage.Close.newBuilder((cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            closeDataBuilder_.mergeFrom(value);
          }
          closeDataBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public Builder clearCloseData() {
        if (closeDataBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          closeDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder getCloseDataBuilder() {
        return getCloseDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      public cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder getCloseDataOrBuilder() {
        if ((dataBodyCase_ == 3) && (closeDataBuilder_ != null)) {
          return closeDataBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_;
          }
          return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.Close closeData = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.xvkang.phone.netty.protobuf.MyMessage.Close, cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder> 
          getCloseDataFieldBuilder() {
        if (closeDataBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
          }
          closeDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.xvkang.phone.netty.protobuf.MyMessage.Close, cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder, cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder>(
                  (cn.xvkang.phone.netty.protobuf.MyMessage.Close) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return closeDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Data)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Data)
    private static final cn.xvkang.phone.netty.protobuf.MyMessage.Data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.xvkang.phone.netty.protobuf.MyMessage.Data();
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Data>
        PARSER = new com.google.protobuf.AbstractParser<Data>() {
      @java.lang.Override
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.xvkang.phone.netty.protobuf.MyMessage.Data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OpenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Open)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 2;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code tutorial.Open}
   */
  public  static final class Open extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Open)
      OpenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Open.newBuilder() to construct.
    private Open(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Open() {
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Open();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Open(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              email_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Open_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Open_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.xvkang.phone.netty.protobuf.MyMessage.Open.class, cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Open)) {
        return super.equals(obj);
      }
      cn.xvkang.phone.netty.protobuf.MyMessage.Open other = (cn.xvkang.phone.netty.protobuf.MyMessage.Open) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.xvkang.phone.netty.protobuf.MyMessage.Open prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Open}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Open)
        cn.xvkang.phone.netty.protobuf.MyMessage.OpenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Open_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Open_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.xvkang.phone.netty.protobuf.MyMessage.Open.class, cn.xvkang.phone.netty.protobuf.MyMessage.Open.Builder.class);
      }

      // Construct using cn.xvkang.phone.netty.protobuf.MyMessage.Open.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Open_descriptor;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Open getDefaultInstanceForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance();
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Open build() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Open result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Open buildPartial() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Open result = new cn.xvkang.phone.netty.protobuf.MyMessage.Open(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.email_ = email_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Open) {
          return mergeFrom((cn.xvkang.phone.netty.protobuf.MyMessage.Open)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.xvkang.phone.netty.protobuf.MyMessage.Open other) {
        if (other == cn.xvkang.phone.netty.protobuf.MyMessage.Open.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000002;
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.xvkang.phone.netty.protobuf.MyMessage.Open parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.xvkang.phone.netty.protobuf.MyMessage.Open) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        email_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Open)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Open)
    private static final cn.xvkang.phone.netty.protobuf.MyMessage.Open DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.xvkang.phone.netty.protobuf.MyMessage.Open();
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Open getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Open>
        PARSER = new com.google.protobuf.AbstractParser<Open>() {
      @java.lang.Override
      public Open parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Open(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Open> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Open> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.xvkang.phone.netty.protobuf.MyMessage.Open getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CloseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Close)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 1;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code tutorial.Close}
   */
  public  static final class Close extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Close)
      CloseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Close.newBuilder() to construct.
    private Close(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Close() {
      number_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Close();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Close(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              number_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Close_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Close_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.xvkang.phone.netty.protobuf.MyMessage.Close.class, cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder.class);
    }

    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 1;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string number = 1;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Close)) {
        return super.equals(obj);
      }
      cn.xvkang.phone.netty.protobuf.MyMessage.Close other = (cn.xvkang.phone.netty.protobuf.MyMessage.Close) obj;

      if (hasNumber() != other.hasNumber()) return false;
      if (hasNumber()) {
        if (!getNumber()
            .equals(other.getNumber())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasNumber()) {
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.xvkang.phone.netty.protobuf.MyMessage.Close prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Close}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Close)
        cn.xvkang.phone.netty.protobuf.MyMessage.CloseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Close_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Close_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.xvkang.phone.netty.protobuf.MyMessage.Close.class, cn.xvkang.phone.netty.protobuf.MyMessage.Close.Builder.class);
      }

      // Construct using cn.xvkang.phone.netty.protobuf.MyMessage.Close.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.internal_static_tutorial_Close_descriptor;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Close getDefaultInstanceForType() {
        return cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance();
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Close build() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Close result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.xvkang.phone.netty.protobuf.MyMessage.Close buildPartial() {
        cn.xvkang.phone.netty.protobuf.MyMessage.Close result = new cn.xvkang.phone.netty.protobuf.MyMessage.Close(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.xvkang.phone.netty.protobuf.MyMessage.Close) {
          return mergeFrom((cn.xvkang.phone.netty.protobuf.MyMessage.Close)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.xvkang.phone.netty.protobuf.MyMessage.Close other) {
        if (other == cn.xvkang.phone.netty.protobuf.MyMessage.Close.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          bitField0_ |= 0x00000001;
          number_ = other.number_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.xvkang.phone.netty.protobuf.MyMessage.Close parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.xvkang.phone.netty.protobuf.MyMessage.Close) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.Close)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Close)
    private static final cn.xvkang.phone.netty.protobuf.MyMessage.Close DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.xvkang.phone.netty.protobuf.MyMessage.Close();
    }

    public static cn.xvkang.phone.netty.protobuf.MyMessage.Close getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Close>
        PARSER = new com.google.protobuf.AbstractParser<Close>() {
      @java.lang.Override
      public Close parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Close(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Close> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Close> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.xvkang.phone.netty.protobuf.MyMessage.Close getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Data_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Open_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Open_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Close_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Close_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobuf/my_message.proto\022\010tutorial\"\251\001" +
      "\n\004Data\022*\n\tdata_type\030\001 \002(\0162\027.tutorial.Dat" +
      "a.DataType\022\"\n\010openData\030\002 \001(\0132\016.tutorial." +
      "OpenH\000\022$\n\tcloseData\030\003 \001(\0132\017.tutorial.Clo" +
      "seH\000\"\037\n\010DataType\022\010\n\004OPEN\020\000\022\t\n\005CLOSE\020\001B\n\n" +
      "\010dataBody\"#\n\004Open\022\014\n\004name\030\001 \001(\t\022\r\n\005email" +
      "\030\002 \001(\t\"\027\n\005Close\022\016\n\006number\030\001 \001(\tB+\n\036cn.xv" +
      "kang.phone.netty.protobufB\tMyMessage"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tutorial_Data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Data_descriptor,
        new java.lang.String[] { "DataType", "OpenData", "CloseData", "DataBody", });
    internal_static_tutorial_Open_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_Open_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Open_descriptor,
        new java.lang.String[] { "Name", "Email", });
    internal_static_tutorial_Close_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_Close_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Close_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
